language: csharp
solution: IdleLandsRedux.sln
os:
  - linux
mono:
  - latest
install:
  - nuget restore IdleLandsRedux.sln
  - nuget install NUnit.Console -Version 3.0.1 -OutputDirectory testrunner
before_script:
  - git clone https://github.com/IdleLands/Custom-Assets ./assets
script:
  - xbuild /p:Configuration=Release IdleLandsRedux.sln
  #xbuild doesn't honour the custom commands section of csprojs. Pity.
  - cd ./IdleLandsRedux.GameLogic.Tests
  - ../create_assets_symlink.sh
  - cd ../
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit-console.exe ./IdleLandsRedux.Common.Tests/bin/Release/IdleLandsRedux.Common.Tests.dll
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit-console.exe ./IdleLandsRedux.Contracts.Tests/bin/Release/IdleLandsRedux.Contracts.Tests.dll
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit-console.exe ./IdleLandsRedux.GameLogic.Tests/bin/Release/IdleLandsRedux.GameLogic.Tests.dll
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit-console.exe ./IdleLandsRedux.GameLogic.DataEntities.Tests/bin/Release/IdleLandsRedux.GameLogic.DataEntities.Tests.dll
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit-console.exe ./IdleLandsRedux.InteropPlugins.Tests/bin/Release/IdleLandsRedux.InteropPlugins.Tests.dll
