language: csharp
solution: IdleLandsRedux.sln
os:
  - linux
mono:
  - latest
#this needs sudo stuff, which slows the build, plus code analysis issues don't fail the build.
#before_install:
#  - wget "https://raw.githubusercontent.com/Oipo/travis-mono-scripts/master/gendarme.sh"
#  - sudo chmod a+x gendarme.sh
#  - sudo ./gendarme.sh
install:
  - nuget restore IdleLandsRedux.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
before_script:
  - git clone https://github.com/IdleLands/Custom-Assets ./assets
script:
  - xbuild /p:Configuration=Release IdleLandsRedux.sln
  - ls -1
  - ls -1 assets
  - ls -l IdleLandsRedux.Common.Tests
  - ls -l IdleLandsRedux.Common.Tests/bin
  - ls -l IdleLandsRedux.Common.Tests/bin/Release
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./IdleLandsRedux.Common.Tests/bin/Release/IdleLandsRedux.Common.Tests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./IdleLandsRedux.GameLogic.Tests/bin/Release/IdleLandsRedux.GameLogic.Tests.dll
